name: Rebase Upstream git.icinga.com/build-docker/docs
on:
  schedule:
  - cron: "0 0 * * 0"
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: 10
    - name: Rebase Upstream git.icinga.com/build-docker/docs
      uses: imba-tjd/rebase-upstream-action@0.5
      with:
        upstream: https://git.icinga.com/build-docker/docs.git
        branch:   master
